### ISSUE TITLE
No - Avatar

### ISSUE THREAD

**Issue by Janik-Haag** [Nerdbergev/nerdpoll#3]
Error:
When voting without an Avatar, the widget throws this error
![image](https://user-images.githubusercontent.com/80165193/202787808-ef1e1e59-c0dc-4ebd-82a5-b412d9a50275.png)

Expected result:
Being able to vote

To reproduce:
Use a Matrix account without Avatar and try Voting

**Comment by aylen384** [comment]
I guess we need a fallback to a default icon - I'm using this one here:
https://github.com/asdil12/nerdpoll/blob/master/default_icon.png
![](https://raw.githubusercontent.com/asdil12/nerdpoll/master/default_icon.png)

**Comment by Janik-Haag** [comment]
Das feature funktioniert unter Matrix nicht.
Kriege immer noch die Meldung
![image](https://user-images.githubusercontent.com/80165193/204348609-8d120f05-d66c-4b0e-b20e-4d4b6f9445f6.png)
Nach dem ich allerdings für andere User den placeholder angezeigt bekomme vermute ich das es für Telegram User funktioniert.

![image](https://user-images.githubusercontent.com/80165193/204348776-1d3faf70-df10-489a-bd39-44b0172e16ac.png)

**Comment by MikeTsenatek** [comment]
Jap richtig. Aktuell enforce ich für Matrixuser ein Avatar. Man müsste da mal jemand ein PR schreiben wo man ein Bild für sich hochladen kann, falls in matrix keines gesetzt ist.
